### ISSUE TITLE
Sidebar Doc Click Actions

### ISSUE THREAD

**Issue by dewinterjack** [holistic-web/progress#12]
### Sidebar docs, click functionality

*When you click on a doc in the sidebar, it will open it, if the doc is already open, the title becomes editable (maybe on double click)*

This is waiting on the sidebar/doc list to be merged. #6 

- [ ] Doc title click opens that doc details page.
- [ ] Clicking on doc title when already on that docs detail page makes the title in the sidebar you are clicking editable.
- [ ] Clicking off of the title will save the new name and update it in the details page (that you would already be on)

**Comment by michaelfitzhavey** [comment]
closed since not in progress. migrated to #38
