### ISSUE TITLE
Post preview improvements

### ISSUE THREAD

**Issue by Zimzams** [holistic-web/progress#18]
- [x] in place of "Read Post" button, make the thread title be clickable as "read more"
- [x] Below in the place of where the button used to be give a preview of the post 
- [ ] potentially also meta info about the post, eg date or sub-thread/section of site later on.

**Comment by Charlielancaster** [comment]
When viewing the child posts, it shows the raw version and not the mark down (i.e. shows the # instead of a title)

**Comment by michaelfitzhavey** [comment]
migrated to #17
