### ISSUE TITLE
Site Structure Improvements

### ISSUE THREAD

**Issue by Zimzams** [holistic-web/progress#20]
## Search Function 
- [x] searchbox In header
- [x] opens a new page with related posts
- [x] results page clearly displays the search parameters above results
- [x] filter posts by tags
- [ ] search should search comments

## Sidebar 
- [ ] store list of users top tags

## Homepage
- [ ] Front page displays most viewed / most recently active posts from different tags.

**Comment by michaelfitzhavey** [comment]
https://github.com/holistic-web/progress/pull/23 addresses search function

**Comment by michaelfitzhavey** [comment]
migrated to #38
