### ISSUE TITLE
Searchbar overlaps with button

### ISSUE THREAD

**Issue by SuliR97** [holistic-web/progress#50]
on macbook with retina screen:
<img width="1434" alt="screen shot 2018-09-28 at 19 03 09" src="https://user-images.githubusercontent.com/38366663/46225471-3a23eb80-c351-11e8-9cb0-d61c64b788ed.png">

**Comment by michaelfitzhavey** [comment]
fixed by: https://github.com/holistic-web/progress/commit/ccc0bd0f51348691bf973025d64d2daff541b2d1
